// Tests for colouring a SINGLE part by swapping filament partway up.
//
// The swap must land BETWEEN layers: pausing mid-layer leaves a seam and a
// blob where the nozzle sat, so placement is correctness, not neatness.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { insertColourChanges, bandsToChanges } from "./colourchange";

/** A G-code skeleton with the layer markers PrusaSlicer emits. */
function fakeGcode(layerHeights: number[]): string {
  const out = ["; generated by test", "G21", "G90"];
  for (const z of layerHeights) {
    out.push(";LAYER_CHANGE", `;Z:${z}`, `;HEIGHT:0.2`, `G1 Z${z} F600`, "G1 X10 Y10 E1");
  }
  out.push("; done");
  return out.join("\n");
}

function withGcode(layers: number[], fn: (path: string) => void): void {
  const dir = mkdtempSync(join(tmpdir(), "slicely-cc-"));
  const p = join(dir, "t.gcode");
  writeFileSync(p, fakeGcode(layers));
  try {
    fn(p);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test("bandsToChanges splits a height into equal bands, one swap per boundary", () => {
  // Three colours over 30mm: the first starts on the bed and needs no swap.
  assert.deepEqual(bandsToChanges(30, ["#000000", "#FF0000", "#00FF00"]), [
    { atZ: 10, colourHex: "#FF0000" },
    { atZ: 20, colourHex: "#00FF00" },
  ]);
});

test("bandsToChanges returns nothing for a single colour", () => {
  assert.deepEqual(bandsToChanges(30, ["#000000"]), []);
  assert.deepEqual(bandsToChanges(0, ["#000000", "#FF0000"]), []);
});

test("a swap is inserted immediately before a layer change, never inside a layer", () => {
  withGcode([0.2, 0.4, 0.6, 0.8, 1.0], (p) => {
    const res = insertColourChanges(p, [{ atZ: 0.5, colourHex: "#1E6FC8" }]);
    assert.equal(res.inserted, 1);
    // Quantised up to the first layer at or above the request.
    assert.deepEqual(res.atZ, [0.6]);

    const lines = readFileSync(p, "utf8").split("\n");
    const swap = lines.findIndex((l) => l === "M600");
    assert.ok(swap > 0, "M600 must be present");
    assert.equal(
      lines[swap + 1],
      ";LAYER_CHANGE",
      "the swap must sit immediately before a layer change, not inside a layer",
    );
    assert.equal(lines[swap + 2], ";Z:0.6");
  });
});

test("several swaps land on their own layers, in order", () => {
  withGcode([0.2, 0.4, 0.6, 0.8, 1.0, 1.2], (p) => {
    const res = insertColourChanges(p, [
      { atZ: 0.4, colourHex: "#FF0000" },
      { atZ: 0.9, colourHex: "#00FF00" },
    ]);
    assert.equal(res.inserted, 2);
    assert.deepEqual(res.atZ, [0.4, 1]);
    const g = readFileSync(p, "utf8");
    assert.equal((g.match(/^M600$/gm) ?? []).length, 2);
    assert.ok(g.indexOf("#FF0000") < g.indexOf("#00FF00"), "swaps must stay in height order");
  });
});

test("a change above the model is skipped, not appended to the end", () => {
  withGcode([0.2, 0.4, 0.6], (p) => {
    const res = insertColourChanges(p, [{ atZ: 50, colourHex: "#FF0000" }]);
    assert.equal(res.inserted, 0);
    assert.equal(res.skipped.length, 1);
    assert.ok(
      !readFileSync(p, "utf8").includes("M600"),
      "pausing after the print finished would waste a purge and confuse the user",
    );
  });
});

test("two changes on the same layer collapse to one swap", () => {
  withGcode([0.2, 0.4, 0.6], (p) => {
    const res = insertColourChanges(p, [
      { atZ: 0.35, colourHex: "#FF0000" },
      { atZ: 0.4, colourHex: "#00FF00" },
    ]);
    assert.equal(res.inserted, 1, "one layer boundary can only carry one swap");
    assert.equal((readFileSync(p, "utf8").match(/^M600$/gm) ?? []).length, 1);
  });
});

test("no changes leaves the file byte-identical", () => {
  withGcode([0.2, 0.4], (p) => {
    const before = readFileSync(p, "utf8");
    const res = insertColourChanges(p, []);
    assert.equal(res.inserted, 0);
    assert.equal(readFileSync(p, "utf8"), before);
  });
});
