// Tests for colouring a SINGLE part by swapping filament partway up.
//
// The swap must land BETWEEN layers: pausing mid-layer leaves a seam and a
// blob where the nozzle sat, so placement is correctness, not neatness.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { insertColourChanges, bandsToChanges, stopsToChanges } from "./colourchange";

/** A G-code skeleton with the layer markers PrusaSlicer emits. */
function fakeGcode(layerHeights: number[]): string {
  const out = ["; generated by test", "G21", "G90"];
  for (const z of layerHeights) {
    out.push(";LAYER_CHANGE", `;Z:${z}`, `;HEIGHT:0.2`, `G1 Z${z} F600`, "G1 X10 Y10 E1");
  }
  out.push("; done");
  return out.join("\n");
}

function withGcode(layers: number[], fn: (path: string) => void): void {
  const dir = mkdtempSync(join(tmpdir(), "slicely-cc-"));
  const p = join(dir, "t.gcode");
  writeFileSync(p, fakeGcode(layers));
  try {
    fn(p);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test("bandsToChanges splits a height into equal bands, one swap per boundary", () => {
  // Three colours over 30mm: the first starts on the bed and needs no swap.
  assert.deepEqual(bandsToChanges(30, ["#000000", "#FF0000", "#00FF00"]), [
    { atZ: 10, colourHex: "#FF0000" },
    { atZ: 20, colourHex: "#00FF00" },
  ]);
});

test("bandsToChanges returns nothing for a single colour", () => {
  assert.deepEqual(bandsToChanges(30, ["#000000"]), []);
  assert.deepEqual(bandsToChanges(0, ["#000000", "#FF0000"]), []);
});

test("a swap is inserted immediately before a layer change, never inside a layer", () => {
  withGcode([0.2, 0.4, 0.6, 0.8, 1.0], (p) => {
    const res = insertColourChanges(p, [{ atZ: 0.5, colourHex: "#1E6FC8" }]);
    assert.equal(res.inserted, 1);
    // Quantised up to the first layer at or above the request.
    assert.deepEqual(res.atZ, [0.6]);

    const lines = readFileSync(p, "utf8").split("\n");
    const swap = lines.findIndex((l) => l === "M600");
    assert.ok(swap > 0, "M600 must be present");
    assert.equal(
      lines[swap + 1],
      ";LAYER_CHANGE",
      "the swap must sit immediately before a layer change, not inside a layer",
    );
    assert.equal(lines[swap + 2], ";Z:0.6");
  });
});

test("several swaps land on their own layers, in order", () => {
  withGcode([0.2, 0.4, 0.6, 0.8, 1.0, 1.2], (p) => {
    const res = insertColourChanges(p, [
      { atZ: 0.4, colourHex: "#FF0000" },
      { atZ: 0.9, colourHex: "#00FF00" },
    ]);
    assert.equal(res.inserted, 2);
    assert.deepEqual(res.atZ, [0.4, 1]);
    const g = readFileSync(p, "utf8");
    assert.equal((g.match(/^M600$/gm) ?? []).length, 2);
    assert.ok(g.indexOf("#FF0000") < g.indexOf("#00FF00"), "swaps must stay in height order");
  });
});

test("a change above the model is skipped, not appended to the end", () => {
  withGcode([0.2, 0.4, 0.6], (p) => {
    const res = insertColourChanges(p, [{ atZ: 50, colourHex: "#FF0000" }]);
    assert.equal(res.inserted, 0);
    assert.equal(res.skipped.length, 1);
    assert.ok(
      !readFileSync(p, "utf8").includes("M600"),
      "pausing after the print finished would waste a purge and confuse the user",
    );
  });
});

test("two changes on the same layer collapse to one swap", () => {
  withGcode([0.2, 0.4, 0.6], (p) => {
    const res = insertColourChanges(p, [
      { atZ: 0.35, colourHex: "#FF0000" },
      { atZ: 0.4, colourHex: "#00FF00" },
    ]);
    assert.equal(res.inserted, 1, "one layer boundary can only carry one swap");
    assert.equal((readFileSync(p, "utf8").match(/^M600$/gm) ?? []).length, 1);
  });
});

test("no changes leaves the file byte-identical", () => {
  withGcode([0.2, 0.4], (p) => {
    const before = readFileSync(p, "utf8");
    const res = insertColourChanges(p, []);
    assert.equal(res.inserted, 0);
    assert.equal(readFileSync(p, "utf8"), before);
  });
});

// ── Explicit stops ─────────────────────────────────────────────────────────
// Equal bands answer "make it three colours". They cannot answer "black up to
// 5 mm", "change at layer 40", or "the bottom third in black" — the requests
// people actually make about a two-tone print.

test("stopsToChanges resolves an absolute height straight through", () => {
  assert.deepEqual(stopsToChanges(30, 0.2, [{ atZ: 5, colourHex: "#1E6FC8" }]), [
    { atZ: 5, colourHex: "#1E6FC8" },
  ]);
});

test("stopsToChanges resolves a layer number against the layer height", () => {
  // "Change at layer 40" means layer 40 is the FIRST layer in the new colour.
  // insertColourChanges lands a swap on the first layer whose top is at or
  // above the height, and layer N's top is N * layerHeight — so 40 * 0.2.
  assert.deepEqual(stopsToChanges(30, 0.2, [{ atLayer: 40, colourHex: "#000000" }]), [
    { atZ: 8, colourHex: "#000000" },
  ]);
});

test("stopsToChanges resolves a fraction of the model height", () => {
  assert.deepEqual(stopsToChanges(30, 0.2, [{ atFraction: 1 / 3, colourHex: "#000000" }]), [
    { atZ: 10, colourHex: "#000000" },
  ]);
});

test("a stop at the bed is the STARTING colour, not a swap", () => {
  // The colour a print starts in needs no filament change — it is whatever is
  // already loaded. Emitting a swap at z=0 would pause before the first layer.
  assert.deepEqual(
    stopsToChanges(30, 0.2, [
      { atZ: 0, colourHex: "#000000" },
      { atZ: 10, colourHex: "#1E6FC8" },
    ]),
    [{ atZ: 10, colourHex: "#1E6FC8" }],
  );
  assert.deepEqual(stopsToChanges(30, 0.2, [{ atLayer: 1, colourHex: "#000000" }]), []);
});

test("stops come back in height order however they were given", () => {
  assert.deepEqual(
    stopsToChanges(30, 0.2, [
      { atFraction: 0.5, colourHex: "#00FF00" },
      { atZ: 4, colourHex: "#FF0000" },
      { atLayer: 100, colourHex: "#0000FF" },
    ]),
    [
      { atZ: 4, colourHex: "#FF0000" },
      { atZ: 15, colourHex: "#00FF00" },
      { atZ: 20, colourHex: "#0000FF" },
    ],
  );
});

test("a stop with no usable height, or an unusable colour, is dropped rather than guessed at", () => {
  assert.deepEqual(stopsToChanges(30, 0.2, [{ colourHex: "#FF0000" }]), []);
  assert.deepEqual(stopsToChanges(30, 0.2, [{ atZ: 5, colourHex: "not a colour" }]), []);
});

test("stopsToChanges keeps a too-high stop so the caller can report it as skipped", () => {
  // insertColourChanges already reports out-of-range changes; silently dropping
  // them here would mean the user is never told their "at 90 mm" did nothing.
  assert.deepEqual(stopsToChanges(30, 0.2, [{ atZ: 90, colourHex: "#FF0000" }]), [
    { atZ: 90, colourHex: "#FF0000" },
  ]);
});
