// Reading the colour a downloaded model ALREADY has.
//
// A multi-colour model from Printables or MakerWorld ships its colours inside
// the 3MF — that is what makes it a multi-colour model rather than a shape.
// Slicely used to drop every one of them on the floor and then ask the user
// which colours they wanted, which is a strange question to ask about a model
// whose author already answered it.
//
// Three dialects exist in the wild and all three appear in real downloads:
// PrusaSlicer's, Bambu Studio's (MakerWorld), and the 3MF core spec's own
// material/colour groups.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { readThreeMfColours } from "./threemfColour";
import { writeThreeMfFixture as makeThreeMf } from "./testFixtures";

/** A model document with `count` objects, each carrying `extra` attributes on
 *  its object element and optional per-triangle attributes. */
function modelDoc(objects: Array<{ id: string; objAttrs?: string; triAttrs?: string[] }>): string {
  const res = objects
    .map((o) => {
      const tris = (o.triAttrs ?? ["", "", "", ""]).map(
        (extra, i) => `<triangle v1="0" v2="1" v3="${2 + (i % 2)}" ${extra}/>`,
      );
      return (
        `<object id="${o.id}" type="model" ${o.objAttrs ?? ""}><mesh>` +
        `<vertices>` +
        `<vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/>` +
        `<vertex x="0" y="1" z="0"/><vertex x="0" y="0" z="1"/>` +
        `</vertices>` +
        `<triangles>${tris.join("")}</triangles>` +
        `</mesh></object>`
      );
    })
    .join("");
  const items = objects.map((o) => `<item objectid="${o.id}"/>`).join("");
  return (
    `<?xml version="1.0" encoding="UTF-8"?>` +
    `<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" ` +
    `xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">` +
    `<resources>${res}</resources><build>${items}</build></model>`
  );
}

test("a PrusaSlicer 3MF gives up its per-object extruders and the palette they index", async () => {
  const fixture = makeThreeMf({
    "3D/3dmodel.model": modelDoc([{ id: "1" }, { id: "2" }]),
    "Metadata/Slic3r_PE_model.config":
      `<config>` +
      `<object id="1"><metadata type="object" key="name" value="board"/>` +
      `<metadata type="object" key="extruder" value="1"/></object>` +
      `<object id="2"><metadata type="object" key="name" value="headers"/>` +
      `<metadata type="object" key="extruder" value="2"/></object>` +
      `</config>`,
    // PrusaSlicer stores the print config as commented key/value lines.
    "Metadata/Slic3r_PE.config": `; generated by PrusaSlicer\n; filament_colour = #1E6FC8;#000000\n`,
  });
  try {
    const found = await readThreeMfColours(fixture.path);
    assert.deepEqual(found.palette, ["#1e6fc8", "#000000"]);
    assert.equal(found.objects.length, 2);
    assert.equal(found.objects[0].extruder, 1);
    assert.equal(found.objects[0].colourHex, "#1e6fc8");
    assert.equal(found.objects[0].name, "board");
    assert.equal(found.objects[1].extruder, 2);
    assert.equal(found.objects[1].colourHex, "#000000");
  } finally {
    fixture.cleanup();
  }
});

test("a Bambu/MakerWorld 3MF is read from its own config files", async () => {
  const fixture = makeThreeMf({
    "3D/3dmodel.model": modelDoc([{ id: "1" }, { id: "2" }]),
    "Metadata/model_settings.config":
      `<config>` +
      `<object id="1"><metadata key="name" value="body"/>` +
      `<metadata key="extruder" value="3"/></object>` +
      `<object id="2"><metadata key="name" value="logo"/>` +
      `<metadata key="extruder" value="1"/></object>` +
      `</config>`,
    "Metadata/project_settings.config": JSON.stringify({
      filament_colour: ["#000000", "#FFFFFF", "#008080", "#C81E1E"],
    }),
  });
  try {
    const found = await readThreeMfColours(fixture.path);
    assert.deepEqual(found.palette, ["#000000", "#ffffff", "#008080", "#c81e1e"]);
    assert.equal(found.objects[0].extruder, 3);
    assert.equal(found.objects[0].colourHex, "#008080", "extruder 3 is the third spool");
    assert.equal(found.objects[1].colourHex, "#000000");
  } finally {
    fixture.cleanup();
  }
});

test("core-spec base materials colour an object even with no slicer metadata at all", async () => {
  const fixture = makeThreeMf({
    "3D/3dmodel.model":
      `<?xml version="1.0" encoding="UTF-8"?>` +
      `<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">` +
      `<resources>` +
      `<basematerials id="5">` +
      `<base name="teal" displaycolor="#008080FF"/>` +
      `<base name="black" displaycolor="#000000FF"/>` +
      `</basematerials>` +
      `<object id="1" type="model" pid="5" pindex="1"><mesh>` +
      `<vertices><vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/></vertices>` +
      `<triangles><triangle v1="0" v2="1" v3="2"/></triangles>` +
      `</mesh></object>` +
      `</resources><build><item objectid="1"/></build></model>`,
  });
  try {
    const found = await readThreeMfColours(fixture.path);
    assert.deepEqual(found.palette, ["#008080", "#000000"]);
    assert.equal(found.objects[0].colourHex, "#000000", "pindex 1 is the second base material");
  } finally {
    fixture.cleanup();
  }
});

test("per-triangle painting is read back, PrusaSlicer's dialect", async () => {
  // This is what "the model already had colours on it" means for a single
  // mesh: the author painted regions rather than splitting the model up.
  const fixture = makeThreeMf({
    "3D/3dmodel.model": modelDoc([
      { id: "1", triAttrs: ["", 'slic3rpe:mmu_segmentation="4"', "", 'slic3rpe:mmu_segmentation="8C"'] },
    ]),
  });
  try {
    const found = await readThreeMfColours(fixture.path);
    const paint = found.objects[0].paint;
    assert.ok(paint, "the painting must survive the read");
    assert.equal(paint!.attribute, "slic3rpe:mmu_segmentation");
    assert.equal(paint!.codes.get(1), "4");
    assert.equal(paint!.codes.get(3), "8C");
    assert.equal(paint!.codes.get(0), undefined, "an unpainted triangle carries no code");
  } finally {
    fixture.cleanup();
  }
});

test("per-triangle painting is read back, Bambu's dialect", async () => {
  const fixture = makeThreeMf({
    "3D/3dmodel.model": modelDoc([
      { id: "1", triAttrs: ['paint_color="4"', "", 'paint_color="0C"', ""] },
    ]),
  });
  try {
    const found = await readThreeMfColours(fixture.path);
    const paint = found.objects[0].paint;
    assert.ok(paint);
    assert.equal(paint!.attribute, "paint_color");
    assert.equal(paint!.codes.get(0), "4");
    assert.equal(paint!.codes.get(2), "0C");
  } finally {
    fixture.cleanup();
  }
});

test("a plain 3MF with no colour information says so, rather than inventing a palette", async () => {
  const fixture = makeThreeMf({ "3D/3dmodel.model": modelDoc([{ id: "1" }]) });
  try {
    const found = await readThreeMfColours(fixture.path);
    assert.deepEqual(found.palette, []);
    assert.equal(found.objects[0].colourHex, undefined);
    assert.equal(found.objects[0].paint, undefined);
  } finally {
    fixture.cleanup();
  }
});

test("an unreadable file comes back empty instead of throwing", async () => {
  // Colour is an enhancement to an import. A malformed archive must cost the
  // user their colours, never their model.
  const dir = mkdtempSync(join(tmpdir(), "slicely-3mfc-bad-"));
  const bad = join(dir, "not.3mf");
  writeFileSync(bad, "this is not a zip");
  try {
    const found = await readThreeMfColours(bad);
    assert.deepEqual(found.objects, []);
    assert.deepEqual(found.palette, []);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
